### ISSUE TITLE
Update movements.py to Pybricks 2.0

### ISSUE THREAD

**Issue by TheGreyDiamond** [XilefTech/CharlieOSX#5]
Update the getting of Charlie to new standart in `movements.py`

**Comment by XilefTech** [comment]
you mean the new version of pybricks.....
oh.....
must've forgotten to update it...

**Comment by TheGreyDiamond** [comment]
Good.

**Comment by XilefTech** [comment]
Just had a quick look at the changelog and the code and noticed, that there were no changes to motor implementation. Seems like that was the reason, nothing in there got updated. Anyway, I plan a complete makeover and restructuring of all the code, in which I probably go over everything in more detail and see, if there is anything, I can/should change.

Have you had problems using it to drive with the new pybricks yet?
